Repository CS2103-AY1819S1-F11-2/main, pull requests merged in 2018-10, with the labels that each got.

#44 Update User Guide
  docs/UserGuide.adoc
Labels: docs

#74 AssignCommand and -r flag in AddCommand to assign Room to Guest
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/AssignCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/room/RoomNumber.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AssignCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: feature.major

#73 Add UI Background Files and FXML Files
  src/main/resources/images/SearchIcon.png
  src/main/resources/images/UIBackground.png
  src/main/resources/images/UILoginSidePanel.png
  src/main/resources/view/LoginWindow.fxml
  src/main/resources/view/MainWindowNew.fxml
Labels: feature.minor

#63 [WIP] Expense, Expenses and ExpenseType
  src/main/java/seedu/address/model/expenses/Expense.java
  src/main/java/seedu/address/model/expenses/ExpenseType.java
  src/main/java/seedu/address/model/expenses/Expenses.java
  src/main/java/seedu/address/model/expenses/exceptions/ItemNotFoundException.java
Labels: feature.major, morph.groundwork, priority.High

#66 UserGuide.adoc: Fix numbering bug by adding closing tag to box section
  docs/UserGuide.adoc
Labels: docs

#90 Update list function with flags, add functionality to read and display rooms
  .gitignore
  data/addressbook.xml
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/events/ui/PersonPanelSelectionChangedEvent.java
  src/main/java/seedu/address/commons/events/ui/RoomPanelSelectionChangedEvent.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/storage/XmlAdaptedRoom.java
  src/main/java/seedu/address/storage/XmlSerializableAddressBook.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/RoomCard.java
  src/main/java/seedu/address/ui/RoomListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/RoomListCard.fxml
  src/main/resources/view/RoomListPanel.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CheckoutCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
Labels: priority.High

#89 Expenses again
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Menu.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/expenses/Expense.java
  src/main/java/seedu/address/model/expenses/ExpenseType.java
  src/main/java/seedu/address/model/expenses/Expenses.java
  src/main/java/seedu/address/model/room/Room.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedExpense.java
  src/main/java/seedu/address/storage/XmlAdaptedExpenseType.java
  src/main/java/seedu/address/storage/XmlAdaptedRoom.java
  src/main/java/seedu/address/storage/XmlSerializableAddressBook.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/MenuTest.java
  src/test/java/seedu/address/model/expenses/ExpenseTest.java
  src/test/java/seedu/address/model/expenses/ExpenseTypeTest.java
  src/test/java/seedu/address/model/expenses/ExpensesTest.java
  src/test/java/seedu/address/storage/XmlAdaptedExpenseTest.java
  src/test/java/seedu/address/storage/XmlAdaptedExpenseTypeTest.java
  src/test/java/seedu/address/testutil/RoomBuilder.java
Labels: feature.major, priority.High

#104 Remove AssignCommand and add RoomNumber and BookingPeriod as parameters for the AddCommand
  data/guestlist.xml
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/AssignCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/room/UniqueRoomList.java
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/AssignCommandParserTest.java
  src/test/java/seedu/address/model/room/RoomTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalBookingPeriods.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/TypicalRoomNumbers.java
  src/test/java/seedu/address/testutil/TypicalRooms.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/ModelHelper.java
Labels: feature.major

#110 AddCommand documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: docs

#105 Add CommandArchive
  docs/DeveloperGuide.adoc
  docs/images/CommandArchive_class.PNG
  docs/images/CommandHistory_class.PNG
  src/main/java/seedu/address/logic/CommandArchive.java
  src/main/java/seedu/address/logic/CommandHistory.java
Labels: feature.major

#108 [v1.2] UserGuide update
  data/addressbook.xml
Labels: docs

#115 [v1.2] UI improvements
  commandFile.txt
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/model/expenses/Expenses.java
  src/main/java/seedu/address/model/room/Room.java
  src/main/java/seedu/address/model/room/booking/Booking.java
  src/main/java/seedu/address/model/room/booking/Bookings.java
  src/main/java/seedu/address/model/room/booking/exceptions/NoActiveBookingException.java
  src/main/java/seedu/address/model/room/booking/exceptions/NoActiveOrExpiredBookingException.java
  src/main/java/seedu/address/model/room/booking/exceptions/NoBookingException.java
  src/main/java/seedu/address/ui/RoomCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/RoomListCard.fxml
  src/test/java/seedu/address/model/room/RoomTest.java
Labels: feature.minor

#126 Update README
  README.adoc
Labels: docs

#127 Remove data files and refactor CommandArchive
  .gitignore
  commandFile.txt
  commands_log/commands_log.txt
  data/addressbook.xml
  data/guestlist.xml
  docs/images/Ui.PNG
  src/main/java/seedu/address/logic/CommandArchive.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: severity.Medium

#136 Updates to Expense section of Developer Guide
  docs/DeveloperGuide.adoc
  docs/images/CommandArchive_class.png
  docs/images/CommandHistory_class.png
  docs/images/expense_uml.png
Labels: docs

#147 [v1.3] Refactor room package and fix UI bugs in v1.2
  .gitignore
  commands_log/commands_log.txt
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/CommandHistory.java
  src/main/java/seedu/address/logic/commands/CheckinCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/room/DoubleRoom.java
  src/main/java/seedu/address/model/room/Room.java
  src/main/java/seedu/address/model/room/SingleRoom.java
  src/main/java/seedu/address/model/room/SuiteRoom.java
  src/main/java/seedu/address/model/room/UniqueRoomList.java
  src/main/java/seedu/address/model/room/booking/Booking.java
  src/main/java/seedu/address/model/room/booking/BookingPeriod.java
  src/main/java/seedu/address/model/room/booking/Bookings.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedBooking.java
  src/main/java/seedu/address/storage/XmlAdaptedRoom.java
  src/main/java/seedu/address/ui/RoomCard.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CheckoutCommandTest.java
  src/test/java/seedu/address/model/room/RoomTest.java
  src/test/java/seedu/address/testutil/BookingBuilder.java
  src/test/java/seedu/address/testutil/RoomBuilder.java
  src/test/java/seedu/address/testutil/TypicalBookings.java
  src/test/java/seedu/address/testutil/TypicalRooms.java
  src/test/java/seedu/address/ui/RoomDetailedPanelTest.java
  src/test/java/seedu/address/ui/RoomListPanelTest.java
Labels: feature.minor, priority.High

#139 Remove delete command
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CheckoutCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SelectCommandParserTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: morph.groundwork

#150 [v1.3] Add sequence diagram for CheckinCommand and update README with Appveyor
  README.adoc
  docs/DeveloperGuide.adoc
  docs/diagrams/CheckinCommandSequenceDiagram.pptx
  docs/images/CheckinCommandSequenceDiagram.png
Labels: docs

#143 Remove address field
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/guest/Address.java
  src/main/java/seedu/address/model/guest/Guest.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedGuest.java
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditGuestDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/guest/AddressTest.java
  src/test/java/seedu/address/model/guest/GuestTest.java
  src/test/java/seedu/address/model/guest/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/guest/UniqueGuestListTest.java
  src/test/java/seedu/address/storage/XmlAdaptedGuestTest.java
  src/test/java/seedu/address/testutil/EditGuestDescriptorBuilder.java
  src/test/java/seedu/address/testutil/GuestBuilder.java
  src/test/java/seedu/address/testutil/GuestUtil.java
  src/test/java/seedu/address/testutil/TypicalGuests.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: morph.groundwork

#142 Resolve issue #141: @link Command does not actually have a link
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
Labels: priority.Low

#154 [v1.3] Fix UI bug
  data/concierge.xml
  src/main/java/seedu/address/commons/events/ui/RoomListChangedEvent.java
  src/main/java/seedu/address/model/guest/Guest.java
  src/main/java/seedu/address/model/room/Room.java
  src/main/java/seedu/address/model/room/booking/Booking.java
  src/main/java/seedu/address/model/room/booking/Bookings.java
  src/main/java/seedu/address/ui/RoomCard.java
  src/main/java/seedu/address/ui/RoomDetailedCard.java
  src/main/java/seedu/address/ui/RoomDetailedPanel.java
  src/main/java/seedu/address/ui/RoomListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/RoomDetailedCard.fxml
  src/main/resources/view/RoomListCard.fxml
Labels: priority.Medium, severity.Low

#156 [v1.3] Add checkout by booking period feature & fix CliSyntax
  src/main/java/seedu/address/logic/CommandHistory.java
  src/main/java/seedu/address/logic/commands/CheckoutCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/CheckoutCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Concierge.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/room/Room.java
  src/main/java/seedu/address/model/room/booking/Booking.java
  src/main/java/seedu/address/model/room/booking/BookingPeriod.java
  src/main/java/seedu/address/ui/RoomDetailedPanel.java
  src/main/java/seedu/address/ui/UiManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CheckoutCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/CheckoutCommandParserTest.java
  src/test/java/seedu/address/model/room/RoomTest.java
  src/test/java/seedu/address/ui/MainWindowGuiChangeTest.java
Labels: feature.minor, priority.High

#155 Expenses refactoring
  src/main/java/seedu/address/model/expenses/Expense.java
  src/main/java/seedu/address/model/expenses/ExpenseType.java
  src/main/java/seedu/address/model/expenses/Expenses.java
  src/main/java/seedu/address/model/expenses/Money.java
  src/main/java/seedu/address/model/expenses/exceptions/MoneyLimitExceededException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedExpense.java
  src/main/java/seedu/address/storage/XmlAdaptedExpenseType.java
  src/main/java/seedu/address/ui/RoomDetailedCard.java
  src/test/java/seedu/address/model/ConciergeTest.java
  src/test/java/seedu/address/model/expenses/ExpenseTest.java
  src/test/java/seedu/address/model/expenses/ExpenseTypeTest.java
  src/test/java/seedu/address/model/expenses/ExpensesTest.java
  src/test/java/seedu/address/model/expenses/MoneyTest.java
  src/test/java/seedu/address/storage/XmlAdaptedExpenseTest.java
  src/test/java/seedu/address/storage/XmlAdaptedExpenseTypeTest.java
  src/test/java/seedu/address/testutil/ExpenseBuilder.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: priority.High

#159 Add RepoSense config file
  _reposense/config.json
Labels: type.Task

#162 Update ClearCommand to keep 100 rooms, Update sample Concierge
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/model/Concierge.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/room/Room.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/guitests/guihandles/RoomCardHandle.java
  src/test/java/seedu/address/testutil/ListUtil.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/ConciergeSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/SampleDataTest.java
Labels: morph.groundwork, priority.High

#153 Fix merge conflict errors
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/data/XmlUtilTest/missingGuestField.xml
  src/test/data/XmlUtilTest/validGuest.xml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: severity.Medium, type.Bug
